apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: {{ quote .Values.moodleIngress.enableAccessLog }}
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.moodleIngress.host }}
  name: moodle-ingress
spec:
  rules:
  - host: {{ .Values.moodleIngress.host }}
    http:
      paths:
      - path: {{ .Values.moodleIngress.path }}
        backend:
          serviceName: {{ .Values.ngnixDeploy.name }}
          servicePort: {{ .Values.ngnixDeploy.port }}